{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SalesRep\",\"Sales\",\"Region\",\"Product\",\"Customer\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1451.0 (25.03)+5007b75f0f7edbed506e31fcb76584cd6d711788"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_50f8b88d-5a77-4b05-9f81-53fbce1ae69d",
        "fromColumn": "RegionID",
        "fromTable": "Sales",
        "toColumn": "RegionID",
        "toTable": "Region"
      },
      {
        "name": "AutoDetected_b062600d-37c6-431c-a73d-508303540320",
        "fromColumn": "ProductID",
        "fromTable": "Sales",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "AutoDetected_3f46e4a8-ff42-4140-9bb1-7fcbdd1fb7d9",
        "fromColumn": "CustomerID",
        "fromTable": "Sales",
        "toColumn": "CustomerID",
        "toTable": "Customer"
      },
      {
        "name": "f062bf40-e843-65f6-17da-cfe2bff4dffe",
        "fromColumn": "SalesRepID",
        "fromTable": "Sales",
        "toColumn": "SalesRepID",
        "toTable": "SalesRep"
      },
      {
        "name": "52ec0742-753a-4e6d-8b34-dde0e76aa2b7",
        "fromColumn": "DateKey",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_18ec4583-0cdc-4dc4-88bd-db5c0bcbbbb2"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "SalesRep",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesRepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f852ebb-ef1a-4440-8510-d56ed5dd3d80",
            "sourceColumn": "SalesRepID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesRepName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccbccb75-4e85-489a-8cf7-d108e183c030",
            "sourceColumn": "SalesRepName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "51d30ddb-3def-46a0-b337-8814a88be790",
        "partitions": [
          {
            "name": "SalesRep",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AdithyaKasturi\\Downloads\\OrderDetails_Data\\OrderDetails_Data\\SalesRep.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesRepID\", Int64.Type}, {\"SalesRepName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3132a8b9-0560-4009-9b93-819ab8e60abe",
            "sourceColumn": "OrderID",
            "summarizeBy": "count"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c8e93481-e9ab-448a-8fa9-3c5ee1c1afaa",
            "sourceColumn": "DateKey",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_18ec4583-0cdc-4dc4-88bd-db5c0bcbbbb2"
                },
                "isDefault": true,
                "relationship": "52ec0742-753a-4e6d-8b34-dde0e76aa2b7"
              }
            ]
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebe256af-8f62-40bc-ae25-07e0c55c5632",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ab276ea-290c-4295-a24e-b0afdce9c6bf",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a2b3715-5411-449c-8630-7a3b4fb6cdd0",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesRepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ab775dc-2b44-4369-8be3-dd62751e6a10",
            "sourceColumn": "SalesRepID",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e379c91-9d43-4198-b8fe-fcfce9c8f0e3",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94a2e1e3-ceca-4edd-9ca1-c46c6a12c798",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "20fcbcf6-8e37-45fa-87b4-b69bab17e510",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AdithyaKasturi\\Downloads\\OrderDetails_Data\\OrderDetails_Data\\Sales.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderID\", Int64.Type}, {\"DateKey\", type date}, {\"CustomerID\", Int64.Type}, {\"ProductID\", Int64.Type}, {\"RegionID\", Int64.Type}, {\"SalesRepID\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"SalesAmount\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Region",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f03d4e09-5086-4729-80ef-59410ceff85e",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe0637d9-c0a3-44c6-a229-3b86341acac5",
            "sourceColumn": "RegionName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "376a8a1a-f4db-41eb-ab48-3e5b7d01023e",
        "partitions": [
          {
            "name": "Region",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AdithyaKasturi\\Downloads\\OrderDetails_Data\\OrderDetails_Data\\Region.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"RegionID\", Int64.Type}, {\"RegionName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "feb79a03-497d-4ef2-bc13-6f0e3d0f1490",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9596d32-f29f-4a8d-a817-772873626806",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5e38aaa-a8db-4b99-b0f1-bdb6edf3f12c",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b8c5c9a-7f7b-4e45-b6ce-7b58c7cae57a",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "12b8c163-0a6a-42c8-ac29-899ab56c9aba",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AdithyaKasturi\\Downloads\\OrderDetails_Data\\OrderDetails_Data\\Product.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", Int64.Type}, {\"ProductName\", type text}, {\"Category\", type text}, {\"UnitPrice\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94f179d6-6af1-4dae-9599-fbba8a47f4f1",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d60fb60c-6eec-4832-808b-d50a12be7b2b",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a169f1e7-bcf8-4800-95a9-3bf0c3e36a44",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b866607-6832-45bf-973e-50a5cef69748",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AdithyaKasturi\\Downloads\\OrderDetails_Data\\OrderDetails_Data\\Customer.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerID\", Int64.Type}, {\"CustomerName\", type text}, {\"Segment\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9b2af092-f05d-4ffd-b6eb-55f19348f7ce",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "23bf4167-1f2f-48ac-8ca6-825a9efa18ab",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd848860-888f-47fa-a00b-177a1f952ce0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a2a58d3-f5dc-473c-9218-e17a24477563",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2392f365-1311-46f2-8e1b-0647eeec7976",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "30db6ebf-60f2-4470-a370-5224b8888c64",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "341e950c-ca84-408f-bfc7-60e90ce32fcc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20934283-e815-48db-8905-5193e73ee5bb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4de0183f-c841-4d24-a001-14b7c08a2159",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e73b1add-4e80-43a1-8eea-581abafd4ac2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "733b491f-8727-4da1-a6d8-fa7fdd905fc6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0c83f0e8-b20d-45ba-a60e-d360f7332537",
                "ordinal": 3
              }
            ],
            "lineageTag": "64903fe0-ea24-4a92-a750-3cdacb9d370d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cfbd1a0d-a123-4680-939a-45545786aa48",
        "partitions": [
          {
            "name": "DateTableTemplate_9b2af092-f05d-4ffd-b6eb-55f19348f7ce",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_18ec4583-0cdc-4dc4-88bd-db5c0bcbbbb2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a2d2d2c-bac6-4d3a-805a-fc52de6be3f2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "63be73d8-1977-4368-be6c-a5b3b3c0d865",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "56dcddf1-2f8d-402d-bd94-fef248fd9e79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dc6239da-60fd-4e0b-9dfa-f4bd74892720",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "273d8e9f-000d-4476-897e-8f6a82236b67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "49d3c44a-f9df-4a93-a307-57c273a2b833",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3fe440d9-5c23-4600-b245-e01092459e3a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6b538b9e-58b9-4f9b-9545-9bf30dce362e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d50af756-6484-43e6-b71d-531d0cfcdc6d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b79f6833-e9d8-46c5-bae6-eb4ee3fadff8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3a845584-372e-4883-ba99-f81c3a501bd4",
                "ordinal": 3
              }
            ],
            "lineageTag": "428a7236-425e-4549-b4e7-c8115fc82d7f"
          }
        ],
        "isHidden": true,
        "lineageTag": "517b7ad4-4485-4424-814c-390b1b996990",
        "partitions": [
          {
            "name": "LocalDateTable_18ec4583-0cdc-4dc4-88bd-db5c0bcbbbb2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[DateKey])), 1, 1), Date(Year(MAX('Sales'[DateKey])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}